AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyPythonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: ./python
      CompatibleRuntimes:
        - python3.13
    Metadata:
      BuildMethod: python3.13 